export  const GET_CONTACTS_LOAD = "GET_CONTACTS_LOAD";
export  const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";;
export  const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";


export const DELETE_CONTACT = "DELETE_CONTACT";
export  const GET_CONTACT= "GET_CONTACT";
export  const POST_CONTACT= "POST_CONTACT";
export  const EDIT_CONTACT= "EDIT_CONTACT";
